// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACNoRwygcGpefFlyOWmyqc8ZI64YOs9Xc',
    appId: '1:181396327860:web:75c1de677b887ffbbbf6e1',
    messagingSenderId: '181396327860',
    projectId: 'pavdev-e991f',
    authDomain: 'pavdev-e991f.firebaseapp.com',
    storageBucket: 'pavdev-e991f.appspot.com',
    measurementId: 'G-JFLLG3G8NS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkLLEKXBebwv1h9mLAOKrtAvoexAE7jUc',
    appId: '1:181396327860:android:6845874667cfc4d9bbf6e1',
    messagingSenderId: '181396327860',
    projectId: 'pavdev-e991f',
    storageBucket: 'pavdev-e991f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFgHhA-d12P7s79rA7Ju1jxhbvCWUnRog',
    appId: '1:181396327860:ios:9300298746b211ffbbf6e1',
    messagingSenderId: '181396327860',
    projectId: 'pavdev-e991f',
    storageBucket: 'pavdev-e991f.appspot.com',
    iosBundleId: 'com.example.musicefreixdevgrp22024',
  );

}